services:
  deposit:
    image: deposit:latest
    build:
      context: bank-services
      dockerfile: Dockerfile.deposit
    container_name: deposit
    restart: unless-stopped
    ports:
      - 28080:8080
    volumes:
      - ./search-service/pkg/config/api/config.yaml:/config.yaml

