name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Lint & Format Go Code
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:latest
    env:
      GOFLAGS: -buildvcs=false
    defaults:
      run:
        working-directory: bank-services
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y make
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/yoheimuta/protolint/cmd/protolint@v0.53.0

      - name: ProtoLint
        run: protolint lint proto/

      - name: Goimports Check
        run: goimports -l -w .

      - name: GolangCI-Lint (only gocritic)
        run: golangci-lint run -E gocritic -v ./...
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:27.1.1-dind-alpine3.20
        options: >-
          --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Docker Compose availability
        run: |
          # Use Docker Compose plugin (docker compose) instead of docker-compose
          docker compose version || true

      - name: Run Tests
        run: make test